packages:
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - msw
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - prisma
