allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/engines': set this to true or false
  '@swc/core': set this to true or false
  msw: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - msw
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - prisma
patchedDependencies:
  node-taglib-sharp@6.0.1: patches/node-taglib-sharp@6.0.1.patch
